/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tr.tmg.murat.guvenc;

public class CommunicationModuleJNI {
  public final static native long new_RvmsClient(String jarg1, int jarg2);
  public final static native void delete_RvmsClient(long jarg1);
  public final static native void RvmsClient_start(long jarg1, RvmsClient jarg1_, byte[] jarg2);
  public final static native void RvmsClient_stop(long jarg1, RvmsClient jarg1_);
  public final static native void RvmsClient_initialize();
  public final static native void RvmsClient_readSensor(long jarg1, RvmsClient jarg1_);
  public final static native void RvmsClient_moveRight(long jarg1, RvmsClient jarg1_);
  public final static native void RvmsClient_moveUp(long jarg1, RvmsClient jarg1_);
  public final static native void RvmsClient_moveDown(long jarg1, RvmsClient jarg1_);
  public final static native void RvmsClient_moveLeft(long jarg1, RvmsClient jarg1_);
}
