/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tr.tmg.murat.guvenc;

public class Decode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Decode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Decode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WebcamModuleJNI.delete_Decode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Decode(int width, int height) {
    this(WebcamModuleJNI.new_Decode(width, height), true);
  }

  public FrameBuffer decode(FrameBuffer buffer) {
    return new FrameBuffer(WebcamModuleJNI.Decode_decode(swigCPtr, this, FrameBuffer.getCPtr(buffer), buffer), true);
  }

}
