/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tr.tmg.murat.guvenc;

public class Webcam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Webcam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Webcam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        WebcamModuleJNI.delete_Webcam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Webcam(String url, int width, int height, int codec, int fps) {
    this(WebcamModuleJNI.new_Webcam(url, width, height, codec, fps), true);
  }

  public FrameBuffer getFrame() {
    return new FrameBuffer(WebcamModuleJNI.Webcam_getFrame(swigCPtr, this), true);
  }

}
